spring.application.name=DSA Code Analyzer Backend

# Server configuration
# Defaults to 8080 if PORT is not provided in the environment
server.port=${PORT:8080}
# server.servlet.context-path=/api

# Gemini API Configuration
# This will crash on startup if GEMINI_API_KEY is missing (which is what you want for safety)
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# Logging
logging.level.root=INFO
logging.level.com.dsa.analyzer=DEBUG

frontend.url=${FRONTEND_URL}